module.exports = {
    en: {
        translation: {
            WELCOME_MSG_INIT: `Welcome to the Christian Podcast. With the Christian Podcast, you can easily listen to the latest episodes featured on Edifi along with popular channels, you can say, begin the podcast, to start, or say help, to check more functions! `,
            WELCOME_MSG: `Welcome to the Christian Podcast, you can say, begin the podcast, to start, or say help, to check more functions! `,
            WELCOME_MSG_REPROMPT: 'You can say, begin the podcast, to start.',
            WELCOME_BACK_MSG: `You were listening to {{description}} . Would you like to resume?`,
            WELCOME_BACK_MSG_REPROMPT: 'You can say yes to resume or no to next step.',
            FALLBACK_MSG: `Sorry, I don't know about that. Please try again.`,
            REPROMPT_MSG: `If you're not sure what to do next try asking for help. If you want to leave just say stop. What would you like to do next? `,
            REFLECTOR_MSG: 'You just triggered {{intent}}',
            ERROR_MSG: 'Sorry, there was an error. Please try again.',
            DEVELOPING_MSG: 'Sorry, This feature is not currently supported!',
            BUILT_IN_HELP_WEL_VERSE:'Welcome to the Christian Podcast! Christian Podcast can help you easily listen to the latest episodes along with popular channels on Edifi. ',
            HELP_IN_LISENING_MSG: `You are listening to  {{description}} . You can say, Alexa, see playlist, to look through the playlist. You can also say, Alexa, see channel list, to check recommended channels! Or say, Alexa, search channels or episodes, to search channels or episodes. `,
            HELP_IN_QUESTION_MSG: `You can see channels or featured episodes list by saying, Alexa, see channel list , or Alexa, see featured episodes list. You can use numbers, instead of names by saying, Alexa, episode {{number1}} or channel {{number2}}, to start the podcast. `,
            HELP_IN_SEARCH_MSG: ['You can also search channels or episodes by saying, Alexa, search channels, or Alexa, search episodes. ', 'Or say, Alexa, search, to search channels or episodes. '],
            GOODBYE_MSG: ['Goodbye! ', 'So long! ', 'See you later! ', 'Cheers! '],
            PROGRESSIVE_MSG: 'Let me {{description}} ',
            UPDATELATEST_RESOURCES_PROGRESSIVE_MSG: ['OK! Let me first update latest resources for you... ', 'Got it! Let me first update latest resources for you...  ', 'No Problem! Let me first update latest resources for you... '],
            START_PLAYING_MSG: `This is  {{description}} . `,
            START_PLAYING_RESUME_MSG: `Last time, You have heard {{description}} around {{time}}. Would you like to resume? `,
            START_PLAYING_RESUME_MSG_REPROMPT: 'You can say yes to resume or no to play from the beigining.',
            START_PLAYING_HELP_MSG: `You can say, Next or Previous to navigate through your playlist. You can also say Alexa, ask Christian Podcast see my playlist, to look through the playlist! Or say, Alexa, ask Christian Podcast play channel + number, to change channel!`,
            START_PLAYING_HELP_MSG_IN_SHORT: `You can say, Next or Previous to navigate through your playlist.`,
            LIST_PROMPT_NOTIFICATION_MSG: `You can use number, instead of name by saying, for example, alexa, {{name}} {{number}}, to start podcasts! `,
            LIST_ONLY_TOP_FIVE_NOTIFICATION_MSG: ` Here are top 5 {{name}} : `,
            LIST_PROMOTION_EPISODES_NOTIFICATION_MSG_FOR_CHANNEL: `{{length}} latest featured episodes are available, you can say alexa, play featured episodes, to change your playlist! `,
            LIST_PROMOTION_EPISODES_NOTIFICATION_MSG_FOR_EPISODES: `{{length}} latest featured episodes are available, also in your playlist. `,
            LIST_PLAYLIST_NOTIFICATION_MSG_HEADER_FRO_CHANNEL: `{{length}} latest episodes from channel {{name}} are available in your playlist. `,
            LIST_PLAYLIST_NOTIFICATION_MSG_HEADER_FRO_PROMOTION: `{{length}} latest featured episodes are available in your playlist. `,
            LIST_PLAYLIST_NOTIFICATION_MSG_HEADER_FRO_EPISODES: `{{length}} episodes are available in your playlist. `,
            LIST_RESULTS_NOTIFICATION_MSG_HEADER_FRO_SEARCH: `Here are {{length}} {{name}} from your{{last}}search results. `,
            LIST_RECOMMANDED_CHANNELS_NOTIFICATION_MSG_HEADER: `Here are {{length}} recommended channels: `,
            API_ERROR_MSG: `I'm sorry, I'm having trouble accessing the external A.P.I., Please try again later. `,
            INDEX_ERROR_MSG: `Oops! {{}} {{}} doesn't exist，you can try a smaller number. `,
            SEARCH_CONFIRMATION_REJECTED_MSG: `Ok, never mind! At any time, you can say Alexa, search {{name}} to search.`,
            START_NO_RESUME_RESPONSE_MSG: `Ok, never mind! You can say, Alexa, play featured episodes, to play latest featured episodes. Or say, Alexa, channel list, to look through recommended channels. You can also say, Alexa, search, to search channels or episodes. What would you like to do next? `,
            BUILT_IN_FOOTER_VERSE:'The earth shall be full of the knowledge of the Lord as the waters cover the sea! Isaiah 11:9'
        }
    }
}
